<?php

namespace ciberConnect\shopBundle\Repository;

/**
 * listServiciosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class listServiciosRepository extends \Doctrine\ORM\EntityRepository
{
}
