<?php

namespace ciberConnect\shopBundle\Repository;

/**
 * listGeneroPeliculaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class listGeneroPeliculaRepository extends \Doctrine\ORM\EntityRepository
{
}
