<?php

namespace ciberConnect\shopBundle\Repository;

/**
 * peliculasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class peliculasRepository extends \Doctrine\ORM\EntityRepository
{
}
