services:
   # ciber_connectshop.example:
   #     class: ciberConnect\shopBundle\Example
   #     arguments: ["@service_id", "plain_value", "%parameter%"]
   sonata.admin.peliculas:
      class: ciberConnect\shopBundle\Admin\peliculasAdmin
      arguments: [~,ciberConnect\shopBundle\Entity\peliculas,~]
      tags:
          - { name: sonata.admin, manager_type: orm, label: Peliculas, group: "Peliculas" }
      public: true

   sonata.admin.listGeneroPeliculas:
      class: ciberConnect\shopBundle\Admin\listGeneroPeliculaAdmin
      arguments: [~,ciberConnect\shopBundle\Entity\listGeneroPelicula,~]
      tags:
          - { name: sonata.admin, manager_type: orm, label: Genero, group: "Peliculas" }
      public: true
